biokingdom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('content/',include('content.urls')),
    path('', include('homepage.urls'))
]

content/urls.py
from django.urls import path, include
from . import views

app_name = 'content'

urlpatterns = [
    path('',views.IndexView, name='coursepage_overview_url'),
    path('Domain/<int:domain_id>/',views.DomainView,name='Domain_url'),
    path('sources/',views.SourceView,name='source_url')
]

homepage/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'homepage'

urlpatterns = [
    path('',views.IndexView, name='homepage_url'),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from django.db import models

class Domain(models.Model):
    title = models.CharField(max_length=150,primary_key=False,default="",null=True)
    description = models.TextField(max_length=10000,primary_key=False,default="")
    characteristics = models.TextField(max_length=10000,primary_key=False,default="")
    divergent_event = models.TextField(max_length=10000,primary_key=False,default="")
    cell_type = models.TextField(max_length=10000,primary_key=False,default="")
    body_plan = models.TextField(max_length=10000,primary_key=False,default="")
    metabolism = models.TextField(max_length=10000,primary_key=False,default="")
    circulatory = models.TextField(max_length=10000,primary_key=False,default="")
    respiratory = models.TextField(max_length=10000,primary_key=False,default="")
    reproduction = models.TextField(max_length=10000,primary_key=False,default="")
    examples = models.TextField(max_length=10000,primary_key=False,default="")
    vocabulary = models.TextField(max_length=10000,primary_key=False,default="")
    keytraits = models.TextField(max_length=10000,primary_key=False,null=True)



    def __str__(self):
        return self.title

#these are the subheadings that each kingdom will have the information to fill out if that makes sense....
class Subheading(models.Model):
    Domain = models.ForeignKey(Domain, on_delete=models.CASCADE, default="")
    title = models.CharField(max_length=150,default="common subheading")
    content = models.TextField(max_length=10000,default='content for this subheading')


    def __str__(self):
        return self.title

class Images(models.Model):
    Domain = models.ForeignKey(Domain,on_delete=models.CASCADE,default="")
    title = models.CharField(max_length=150,primary_key=False,default="",null=True)
    caption = models.TextField(max_length = 1000,primary_key=False,default='pictures caption',blank=True)
    image = models.ImageField(upload_to='images/',blank=True,null=True)


    def __str__(self):
        return self.title

homepage/models.py
from django.db import models

# Create your models here.

content/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse

from .models import *

def IndexView(request):
    domains = Domain.objects.all().order_by('id')
    #return(HttpResponse("Index view"))
    return render(request,'contentpages/domainlist.html',context={'domain': domains})

def DomainView(request,domain_id):
    try:
        CurrentDomain = Domain.objects.get(pk=domain_id)
        CurrentSubheading = Subheading.objects.filter(Domain=CurrentDomain)
        CurrentImageList = Images.objects.filter(Domain=CurrentDomain)
    except (KeyError,Domain.DoesNotExist):
        print("Domain object doesn't exist")
    else:
        print("banana")
        return render(request,'contentpages/domainbase.html',context={'domain':CurrentDomain,'subheading':CurrentSubheading,'image_list': CurrentImageList})

def SourceView(request):
    return render(request,'contentpages/sources.html',context={})

homepage/views.py
from django.shortcuts import render

# Create your views here.

def IndexView(request):
    #return(HttpResponse("Index view"))
    return render(request,'homepagetemplates/homepage.html',context={})

content/templates/contentpages/domainbase.html
{% extends 'contentpages/topbar.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'bass.css' %}">

<html>
{%block content%}

    <div class="flex_container">
        <h1>Welcome to the great <i>{{domain.title}}</i> kingdom!</h1><hr>

    <ol>
        <li><h2>Description/Characteristics:</h2>
            <h3>{{ domain.characteristics }}</h3></li>

        <li><h2>Divergent Event:</h2>
            <h3>{{ domain.divergent_event }}</h3></li>

        <li><h2>Cell Type:</h2>
            <h3>{{ domain.cell_type }}</h3></li>

        <li><h2>Body Plan:</h2>
            <h3>{{ domain.body_plan }}</h3></li>

        <li><h2>Metabolism:</h2>
            <h3>{{ domain.metabolism }}</h3></li>

        <li><h2>Circulatory:</h2>
            <h3>{{ domain.circulatory }}</h3></li>

        <li><h2>Respiratory:</h2>
            <h3>{{ domain.respiratory }}</h3></li>

        <li><h2>Reproduction:</h2>
            <h3>{{ domain.reproduction }}</h3></li>

        <li><h2>Examples:</h2>
            <h3>{{ domain.examples }}</h3></li>

        <li><h2>Keytraits(may not apply for all)</h2>
            <h3>{{ domain.keytraits }}</h3></li>

        <li><h2>Vocabulary:</h2>
            <h3>{{ domain.vocabulary }}</h3></li>

        <li><h2>Divergent Event:</h2>
            <h3>{{ domain.divergent_event }}</h3></li>


    </ol>
    <h2>Additional information about the {{ domain.title }} kingdom! </h2>
    <h3>Everything for "additional information" part of the assignment will go here.</h3>
    {% for subheading in domain.subheading_set.all %}
        <ul>
            <li>
                <h2>{{subheading.title}}</h2>
                <h3>{{subheading.content|linebreaks}}</h3>
            </li>
        </ul>

    {% endfor%}
        </div>

<div class="imagediv">
    {% for image in image_list %}
    <h2>{{image.title}}</h2>
    <img src="{{image.image.url}}" alt="{{image.caption}}">
    <h3>{{image.caption}}</h3>
    {% endfor %}

</div>

</div>
{%endblock%}
</html>

content/templates/contentpages/domainlist.html
{% extends 'contentpages/topbar.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'bass.css' %}">

{% block content %}
<div class="flex_container">
    <h1>Visit each link to learn about each kingdom!<hr></h1>
{% for domain in domain %}
    <br><h1><a href="{% url 'content:Domain_url' domain.id %}">{{ domain.title }}</a></h1><hr>
    <br><h3>Description: {{domain.description}}</h3>
{% endfor %}
</div>


{% endblock %}

content/templates/contentpages/sources.html
{% extends 'contentpages/topbar.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'bass.css' %}">

{% block content %}
<div class="flex_containter" id="homepageflex">
<h1>Sources:</h1><hr>

    <h2>Information Sources:</h2>
    <h3><i>Please note some links are broken for some reason...</i></h3>
<ul>
    <li><h3><a href="https://bio.libretexts.org/Bookshelves/Introductory_and_General_Biology/Book%3A_General_Biology_(Boundless)/24%3A_Fungi/24.01%3A_Characteristics_of_Fungi/24.1B%3A_Fungi_Cell_Structure_and_Function#:~:text=Most%20fungi%20are%20multicellular%20organisms,of%20hyphae%20is%20a%20mycelium.">Fungi Cell Structure and Function</a></h3></li>
    <li><h3><a href="https://organismalbio.biosci.gatech.edu/biodiversity/fungi-2/">Organism Biology (Ga Tech)</a></h3></li>
    <li><h3><a href="http://www2.clarku.edu/faculty/dhibbett/tftol/content/3interaction.html#:~:text=All%20fungi%20are%20heterotrophic%2C%20which,from%20living%20or%20dead%20organisms."></a>Teaching the Fungal Tree</h3></li>
    <li><h3><a href="http://www.biology.lifeeasy.org/7021/economic-importance-of-basidiomycetes">Economic Importance of Basidiomycetes</a></h3></li>
    <li><h3><a href="https://www.britannica.com/science/Basidiomycota">Phylum of Fungi</a></h3></li>
    <li><h3><a href="https://bio.libretexts.org/Bookshelves/Introductory_and_General_Biology/Book%3A_General_Biology_(Boundless)/24%3A_Fungi/24.03%3A_Classifications_of_Fungi/24.3E%3A_Deuteromycota_-_The_Imperfect_Fungi">The Imperfect Fungi</a></h3></li>
    <li><h3><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4464818/#:~:text=The%20Zygomycota%20represent%20an%20important,underlying%20immune%20or%20metabolic%20disorders.">Emerging Zygomycetes</a></h3></li>
    <li><h3><a href="https://www.pthorticulture.com/en/training-center/basics-of-plant-respiration/#:~:text=As%20with%20photosynthesis%2C%20plants%20get,dark%20respiration%20and%20photo%20respiration">Photosynthesis Plants Get Dark...Respiration</a></h3></li>
    <li><h3><a href="https://www.researchgate.net/profile/Lakna-Panawala/publication/316617126_Difference_Between_Archaebacteria_and_Eubacteria/links/5907e86baca272116d3cb691/Difference-Between-Archaebacteria-and-Eubacteria.pdf">Difference between the Prokaryotic Bacteria</a></h3></li>
    <li><h3><a href="Pixabay.com">ALL IMAGES</a></h3></li>


</ul>

</div>
{% endblock %}

content/templates/contentpages/topbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'base.css' %}">



<div class="title">
            <title>
            {% block title %}
            {% endblock %}
            </title>
        </div>

    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    </head>

        <div class="topbar" id="topbar">
                <a href="/">Homepage</a>
                <a href="/content/">Website Contents</a>
                <a href="/content/sources/">Sources</a>
            </ul>
        </div>
        <div class="blockcontent">
            {% block content %}
            {% endblock %}
        </div>


homepage/templates/homepagetemplates/homepage.html
{% extends 'contentpages/topbar.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'bass.css' %}">

{% block content %}
<div class="flex_containter" id="homepageflex">
<h1>Welcome to Noah and Stephen's Website! </h1><hr>

<ul>
    <li><h3>This website was made for an AP biology assignment investigating organism kingdoms.</h3></li>
    <li><h3>This website was made from <i>scratch</i> by Noah using Django.</h3></li>
    <li><h4>Due to internet issues and underestimating the difficulty of django...its 5:30am</h4></li>
    <li><h4><i>Because this website was 100% Noah's work...no scissors Stephen.</i></h4></li>
</ul>

    <h2>Please navigate to "Website Contents" to begin your research!</h2><br>

</div>
{% endblock %}